apiVersion: v1
kind: Service
metadata:
  name: ostad-project-10-canary-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      nodePort: 30082
  selector:
    app: ostad-project-10-canary
