apiVersion: apps/v1
kind: Deployment
metadata:
  name: ostad-project-10-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ostad-project-10
      color: green
  template:
    metadata:
      labels:
        app: ostad-project-10
        color: green
    spec:
      containers:
        - name: app
          image: mahmudunnabikajal/ostad-project-10:v2
          env:
            - name: VERSION
              value: "v2"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 2
            periodSeconds: 2
