apiVersion: v1
kind: Service
metadata:
  name: ostad-project-10-rolling-svc
spec:
  selector:
    app: ostad-project-10-rolling
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30081
